"""Choose how the proxy reaches the remote BPS service.

Auto mode is the Windows-safe default: try a direct socket first so a TUN
owns the route, then retry through the environment proxy when the direct
connection cannot be opened. Explicit modes remain available for machines
that need one fixed route.
"""

from __future__ import annotations

import logging
import os
from urllib import error, request

MODES = frozenset({"auto", "system", "direct", "proxy"})
log = logging.getLogger("bps_proxy")


def mode() -> str:
    default = "system"
    value = os.environ.get("BPS_UPSTREAM_MODE", default).strip().lower()
    if value not in MODES:
        raise ValueError(
            f"BPS_UPSTREAM_MODE must be one of {', '.join(sorted(MODES))}"
        )
    return value


def description() -> str:
    selected = mode()
    if selected == "auto":
        return "auto (direct/TUN first, system proxy fallback)"
    if selected == "direct":
        return "direct (system/TUN routing)"
    if selected == "proxy":
        proxy = os.environ.get("BPS_UPSTREAM_PROXY", "").strip()
        return "proxy (configured)" if proxy else "proxy (missing BPS_UPSTREAM_PROXY)"
    return "system (urllib environment proxies)"


def _direct_opener():
    return request.build_opener(request.ProxyHandler({}))


def _system_opener():
    return request.build_opener()


def _proxy_opener(proxy: str):
    return request.build_opener(
        request.ProxyHandler({"http": proxy, "https": proxy})
    )


def open_url(req, *, timeout: float):
    selected = mode()
    if selected == "system":
        return _system_opener().open(req, timeout=timeout)
    if selected == "direct":
        return _direct_opener().open(req, timeout=timeout)
    if selected == "proxy":
        proxy = os.environ.get("BPS_UPSTREAM_PROXY", "").strip()
        if not proxy:
            raise OSError(
                "BPS_UPSTREAM_MODE=proxy requires BPS_UPSTREAM_PROXY, "
                "for example http://127.0.0.1:7890"
            )
        return _proxy_opener(proxy).open(req, timeout=timeout)

    # Auto mode preserves TUN routing whenever it works. Only failures while
    # opening the direct connection are retried; HTTP responses are never
    # duplicated through a second route.
    try:
        return _direct_opener().open(req, timeout=timeout)
    except error.HTTPError as direct_error:
        # A gateway generated by the TUN/egress path is a route failure too.
        # Retry only transient gateway statuses; preserve auth and request
        # errors (401/403/4xx) instead of hiding a real upstream response.
        if direct_error.code not in {502, 503, 504}:
            raise
        log.warning(
            "direct upstream gateway failed; trying system proxy status=%s",
            direct_error.code,
        )
        try:
            direct_error.close()
        except Exception:
            pass
        return _system_opener().open(req, timeout=timeout)
    except (error.URLError, OSError) as direct_error:
        log.warning(
            "direct upstream route failed; trying system proxy "
            "exception_type=%s reason_type=%s",
            type(direct_error).__name__,
            type(getattr(direct_error, "reason", None)).__name__,
        )
        return _system_opener().open(req, timeout=timeout)
